package math.algebra.geometry;

/**
 * A scheme is a ringed space that is locally isomorphic to an affine scheme.
 * More precisely, a scheme consists of a topological space X (the underlying
 * space of the scheme) and a sheaf OX of commutative rings with a unit on X
 * (the structure sheaf of the scheme); moreover, an open covering (Xi)i∈I of X
 * must exist such that (Xi,OX|Xi) is isomorphic to the affine scheme
 * SpecΓ(Xi,OX) of the ring of sections of O over Xi. A scheme is a
 * generalization of the concept of an algebraic variety. For the history of the
 * concept of a scheme, see [Di], [Sh], [Do].
 * 
 * </h1>Basic concepts and properties
 * <h1>
 * 
 * Let (X,OX) be a scheme. For every point x∈X, the stalk OX,x at x of the sheaf
 * is a local ring; the residue field of this ring is denoted by k(x) and is
 * called the residue field of the point X. As the topological properties of the
 * scheme the properties of the underlying space x are considered (for example,
 * quasi-compactness, connectedness, irreducibility). If P is a property of
 * affine schemes (i.e. a property of rings), then one says that a scheme has
 * property P locally if any of its points has an open affine neighbourhood that
 * has this property. The property of being locally Noetherian is an example of
 * this (see Noetherian scheme). A scheme is regular if all its local rings are
 * regular (cf. Regular ring (in commutative algebra)). Other schemes defined in
 * the same way include normal and reduced schemes, as well as Cohen–Macaulay
 * schemes.
 * 
 * A morphism of schemes is a morphism between them as locally ringed spaces. In
 * other words, a morphism f of a scheme X into a scheme Y consists of a
 * continuous mapping f:X→Y and a homomorphism of the sheaves of rings
 * f∗:OY→f∗OX, where for any point x∈X, the homomorphism of local rings
 * OY,f(x)→f∗OX,x must map maximal ideals to maximal ideals. For any ring A, the
 * morphisms of X into SpecA are in bijective correspondence with the ring
 * homomorphisms A→Γ(X,O). For any point x∈X, its imbedding in X can also be
 * considered as a morphism of schemes Speck(x)→X. An important property is the
 * existence in the category of schemes of direct and fibre products (cf. Fibre
 * product of objects in a category), which generalize the concept of the tensor
 * product of rings. The underlying topological space of the product of two
 * schemes X and Y differs, generally speaking, from the product of the
 * underlying spaces X×Y.
 * 
 * A scheme X endowed with a morphism into a scheme S is called an S-scheme, or
 * a scheme over S. A morphism h:X→Y is called a morphism of S-schemes f:X→S and
 * g:Y→S if f=g∘h. Any scheme can be seen as a scheme over SpecZ. A morphism of
 * base change S′→S permits a transition from the S-scheme X to the S′-scheme
 * XS′=X×SS′ — the fibre product of X and S′. If the underlying scheme S is the
 * spectrum of a ring k, then one also speaks of a k-scheme. A k-scheme X is
 * called a k-scheme of finite type if a finite affine covering (Xi)i∈I of X
 * exists such that the k-algebras Γ(Xi,OX) are generated by a finite number of
 * elements. A scheme of finite type over a field, sometimes requiring
 * separability and completeness, is usually called an algebraic variety. A
 * morphism of k-schemes Speck→X is called a rational point of the k-scheme X;
 * the set of such points is denoted by X(k).
 * 
 * For an S-scheme f:X→S and a point s∈S, the k(s)-scheme f−1(s)=Xs, obtained
 * from X by a base change Speck(s)→X, is called a stalk (or fibre) of the
 * morphism f over s. If, instead of the field k(s) in this definition one takes
 * its algebraic closure, then the concept of a geometric fibre is obtained.
 * Thereby, the S-scheme X can be considered as a family of schemes Xs
 * parametrized by the scheme S. Often, when speaking of families, it is also
 * required that the morphism f be flat (cf. Flat morphism).
 * 
 * Concepts relating to schemes over S are often said to be relative, as opposed
 * to the absolute concepts relating to schemes. In fact, for every concept that
 * is used for schemes there is a relative variant. For example, an S-scheme X
 * is said to be separated if the diagonal imbedding X→X×SX is closed; a
 * morphism f:Z→S is said to be smooth if it is flat and all its geometric
 * fibres are regular. Other morphisms defined in the same way include affine,
 * projective, proper, finite, étale, non-ramified, finite-type, etc. A property
 * of a morphism is said to be universal if it is preserved under any base
 * change.
 * 
 * <h1>Cohomology of schemes</h1>
 * 
 * Studies of schemes and related algebraic-geometric objects can often be
 * divided into two problems — local and global. Local problems are usually
 * linearized and their data are described by some coherent sheaf or by sheaf
 * complexes. For example, in the study of the local structure of a morphism
 * X→S, the sheaves ΩPX/S of relative differential forms (cf. Differential form)
 * are of some importance. The global part is usually related to the cohomology
 * of these sheaves (see, for example, deformation of an algebraic variety).
 * Finiteness theorems are useful here, as are theorems on the vanishing of the
 * cohomology spaces (see Kodaira theorem), duality, the Künneth formula, the
 * Riemann–Roch theorem, etc.
 * 
 * A scheme of finite type over a field C can also be considered as a complex
 * analytic space. Using transcendental methods, it is possible to calculate the
 * cohomology of coherent sheaves; it is more important, however, that it is
 * possible to speak of the complex, or strong, topology on X(C), the
 * fundamental group, the Betti numbers, etc. The desire to find something
 * similar for arbitrary schemes and the far-reaching arithmetical hypotheses
 * put forward (see Zeta-function in algebraic geometry) have led to the
 * construction of different topologies in the category of schemes, the best
 * known of which is the étale topology (cf. Etale topology). This has made it
 * possible to define the fundamental group of a scheme, other homotopy
 * invariants, cohomology spaces with values in discrete sheaves, Betti numbers,
 * etc. (see l-adic cohomology; Weil cohomology; Motives, theory of).
 * 
 * <h1>Construction of schemes.</h1>
 * 
 * In the construction of a concrete scheme one most frequently uses the
 * concepts of an affine or projective spectrum (see Affine morphism; Projective
 * scheme), including the definition of a subscheme by a sheaf of ideals. The
 * construction of a projective spectrum makes it possible, in particular, to
 * construct a monoidal transformation of schemes. Fibre products and glueing
 * are also used in the construction of schemes. Less elementary constructions
 * rely on the concept of a representable functor. By having at one's disposal a
 * good concept of a family of objects parametrized by schemes, and by
 * juxtaposing every scheme S with a set F(S) of families parametrized by S, a
 * contravariant functor F is obtained from the category of schemes into the
 * category of sets (possibly with an additional structure). If the functor F is
 * representable, i.e. if a scheme X exists such that F(S)=Hom(S,X) for any S,
 * then a universal family of objects parametrized by X is obtained. The Picard
 * scheme and Hilbert scheme are constructed in this way (see also Algebraic
 * space; Moduli theory).
 * 
 * One other method of generating new schemes is transition to a quotient space
 * by means of an equivalence relation on a scheme. As a rule, this quotient
 * space exists as an algebraic space. A particular instance of this
 * construction is the scheme of orbits X/G under the action of a group scheme G
 * on a scheme X (see Invariants, theory of).
 * 
 * One of the generalizations of the concept of a scheme is a formal scheme,
 * which may be understood to be the inductive limit of schemes with one and the
 * same underlying topological space.
 */
public interface Scheme
{

}
