/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastmath_BLAS1 */

#ifndef _Included_fastmath_BLAS1
#define _Included_fastmath_BLAS1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fastmath_BLAS1
 * Method:    dgetri
 * Signature: (ZILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_fastmath_BLAS1_dgetri
  (JNIEnv *, jclass, jboolean, jint, jobject, jint, jint, jobject);

/*
 * Class:     fastmath_BLAS1
 * Method:    dsyev
 * Signature: (CCILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_fastmath_BLAS1_dsyev
  (JNIEnv *, jclass, jchar, jchar, jint, jobject, jint, jint, jobject, jobject, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    dgelss
 * Signature: (IIILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IDLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_fastmath_BLAS1_dgelss
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint, jobject, jint, jint, jobject, jint, jdouble, jobject, jobject, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    dpotrf
 * Signature: (ZZILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_fastmath_BLAS1_dpotrf
  (JNIEnv *, jclass, jboolean, jboolean, jint, jobject, jint, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    dgetrf
 * Signature: (ZIILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_fastmath_BLAS1_dgetrf
  (JNIEnv *, jclass, jboolean, jint, jint, jobject, jint, jint, jobject);

/*
 * Class:     fastmath_BLAS1
 * Method:    dscal
 * Signature: (IDLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_fastmath_BLAS1_dscal
  (JNIEnv *, jclass, jint, jdouble, jobject, jint, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    daxpy
 * Signature: (IDLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_fastmath_BLAS1_daxpy
  (JNIEnv *, jclass, jint, jdouble, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    dlassq
 * Signature: (ILjava/nio/ByteBuffer;II)D
 */
JNIEXPORT jdouble JNICALL Java_fastmath_BLAS1_dlassq
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    dgeadd
 * Signature: (IIDLjava/nio/ByteBuffer;IDLjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_fastmath_BLAS1_dgeadd
  (JNIEnv *, jclass, jint, jint, jdouble, jobject, jint, jdouble, jobject, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    dcopy
 * Signature: (ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_fastmath_BLAS1_dcopy
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    zcopy
 * Signature: (ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_fastmath_BLAS1_zcopy
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    dgemm
 * Signature: (ZZZIIIDLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIDLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_fastmath_BLAS1_dgemm
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jint, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    cblas_dgemm
 * Signature: (ZZZIIIDLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIDLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_fastmath_BLAS1_cblas_1dgemm
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jint, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    dgeev
 * Signature: (CCILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_fastmath_BLAS1_dgeev
  (JNIEnv *, jclass, jchar, jchar, jint, jobject, jint, jint, jobject, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint);

/*
 * Class:     fastmath_BLAS1
 * Method:    zgeev
 * Signature: (CCILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_fastmath_BLAS1_zgeev
  (JNIEnv *, jclass, jchar, jchar, jint, jobject, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
