/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastmath_Vector_Sub */

#ifndef _Included_fastmath_Vector_Sub
#define _Included_fastmath_Vector_Sub
#ifdef __cplusplus
extern "C" {
#endif
#undef fastmath_Vector_Sub_serialVersionUID
#define fastmath_Vector_Sub_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
