/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastmath_Vector_Condition */

#ifndef _Included_fastmath_Vector_Condition
#define _Included_fastmath_Vector_Condition
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
