/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastmath_DoubleMatrix */

#ifndef _Included_fastmath_DoubleMatrix
#define _Included_fastmath_DoubleMatrix
#ifdef __cplusplus
extern "C" {
#endif
#undef fastmath_DoubleMatrix_serialVersionUID
#define fastmath_DoubleMatrix_serialVersionUID 1LL
/*
 * Class:     fastmath_DoubleMatrix
 * Method:    cholDowndate
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_fastmath_DoubleMatrix_cholDowndate
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jint, jobject, jint, jint, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     fastmath_DoubleMatrix
 * Method:    cholUpdate
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_fastmath_DoubleMatrix_cholUpdate
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jint, jobject, jint, jint, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     fastmath_DoubleMatrix
 * Method:    dgeqp3
 * Signature: (IILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_fastmath_DoubleMatrix_dgeqp3
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint, jobject, jobject, jint, jobject, jint);

/*
 * Class:     fastmath_DoubleMatrix
 * Method:    dgetrs
 * Signature: (CIILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_fastmath_DoubleMatrix_dgetrs
  (JNIEnv *, jclass, jchar, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     fastmath_DoubleMatrix
 * Method:    dorgqr
 * Signature: (IIILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_fastmath_DoubleMatrix_dorgqr
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint, jobject, jobject, jint);

/*
 * Class:     fastmath_DoubleMatrix
 * Method:    dpotri
 * Signature: (CILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_fastmath_DoubleMatrix_dpotri
  (JNIEnv *, jclass, jchar, jint, jobject, jint);

/*
 * Class:     fastmath_DoubleMatrix
 * Method:    dsytrf
 * Signature: (CILjava/nio/ByteBuffer;IILjava/nio/IntBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_fastmath_DoubleMatrix_dsytrf
  (JNIEnv *, jclass, jchar, jint, jobject, jint, jint, jobject, jobject, jint);

/*
 * Class:     fastmath_DoubleMatrix
 * Method:    dsytri
 * Signature: (CILjava/nio/ByteBuffer;IILfastmath/IntVector;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_fastmath_DoubleMatrix_dsytri
  (JNIEnv *, jclass, jchar, jint, jobject, jint, jint, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
