/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastmath_Vector_VectorSpliterator */

#ifndef _Included_fastmath_Vector_VectorSpliterator
#define _Included_fastmath_Vector_VectorSpliterator
#ifdef __cplusplus
extern "C" {
#endif
#undef fastmath_Vector_VectorSpliterator_MAX_BATCH
#define fastmath_Vector_VectorSpliterator_MAX_BATCH 33554432L
#undef fastmath_Vector_VectorSpliterator_BATCH_UNIT
#define fastmath_Vector_VectorSpliterator_BATCH_UNIT 1024L
#ifdef __cplusplus
}
#endif
#endif
