/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastmath_BufferUtils */

#ifndef _Included_fastmath_BufferUtils
#define _Included_fastmath_BufferUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef fastmath_BufferUtils_BYTES_PER_INTEGER
#define fastmath_BufferUtils_BYTES_PER_INTEGER 4L
/*
 * Class:     fastmath_BufferUtils
 * Method:    copy
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_fastmath_BufferUtils_copy
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     fastmath_BufferUtils
 * Method:    bufferAddress
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_fastmath_BufferUtils_bufferAddress
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
