Document: fastmath
Title: Debian fastmath Manual
Author: <insert document author here>
Abstract: This manual describes what fastmath is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fastmath/fastmath.sgml.gz

Format: postscript
Files: /usr/share/doc/fastmath/fastmath.ps.gz

Format: text
Files: /usr/share/doc/fastmath/fastmath.text.gz

Format: HTML
Index: /usr/share/doc/fastmath/html/index.html
Files: /usr/share/doc/fastmath/html/*.html
