package math.space;

/**
 * Locally convex space
 * 
 * A Hausdorff topological vector space over the field of real or complex
 * numbers in which any neighborhood of the zero element contains a convex
 * Neighborhood of the zero element; in other words, a topological vector space
 * is a locally convex space if and only if the topology of is a Hausdorff
 * locally convex topology. Examples of locally convex spaces (and at the same
 * time classes of locally convex spaces that are important in the theory and
 * applications) are normed spaces, countably-normed spaces and Fréchet spaces
 * (cf. Normed space; Countably-normed space; Fréchet space).
 * 
 * A number of general properties of locally convex spaces follows immediately
 * from the corresponding properties of locally convex topologies; in
 * particular, subspaces and Hausdorff quotient spaces of a locally convex
 * space, and also products of families of locally convex spaces, are themselves
 * locally convex spaces. Let be an upward directed set of indices and a family
 * of locally convex spaces (over the same field) with topologies ; suppose that
 * for any pair , , , there is defined a continuous linear mapping ; let be the
 * subspace of the product whose elements satisfy the relations for all ; the
 * space is called the projective limit of the family with respect to and is
 * denoted by or ; the topology of is the projective topology with respect to
 * the family , where is the restriction to the subspace of the projection . On
 * the other hand, suppose that for any pair , , , there is defined a continuous
 * linear mapping ; let , , be the canonical imbedding of in the direct sum and
 * let be the subspace of generated by the images of all spaces under the
 * mappings , where runs through all pairs in for which . If is closed in , then
 * the locally convex space is called the inductive limit of the family with
 * respect to , and is denoted by or . If is a family of subspaces of a vector
 * space , ordered by inclusion, and the topology induces on for , then the
 * inductive limit of the family is said to be strict. A locally convex space is
 * metrizable if and only if its topology is induced by a sequence of semi-norms
 * (cf. Semi-norm); a locally convex space is normable if and only if it
 * contains a bounded open set (Kolmogorov's theorem). Any finite-dimensional
 * subspace of a locally convex space has a complemented closed subspace. The
 * completion of a locally convex space is a locally convex space, and any
 * complete locally convex space is isomorphic to the projective limit of a
 * family of Banach spaces. The space of continuous linear mappings from a
 * topological vector space into a locally convex space is naturally endowed
 * with the structure of a locally convex space (see also Operator topology)
 * with respect to a given family of bounded subsets of for which the linear
 * hull of its union is dense in . A basis of neighborhoods of zero of the
 * corresponding topology is the family of sets , where runs through and runs
 * through a basis of neighbourhoods of zero in .
 * 
 * A central topic in the theory of locally convex spaces (and also in the
 * theory of topological vector spaces) is the study of the relation of the
 * space with its dual or adjoint space. The foundation of this theory of
 * duality for locally convex spaces is the Hahn–Banach theorem, which implies,
 * in particular, that if is a locally convex space, then its dual space
 * separates the points of .
 * 
 * An essential part of the theory of locally convex spaces is the theory of
 * compact convex sets in a locally convex space. The convex hull and the convex
 * balanced hull (cf. also Balanced set) of a pre-compact set in a locally
 * convex space are pre-compact; if is also quasi-complete, then the closed
 * convex hull of and its closed convex balanced hull are compact. If and are
 * disjoint non-empty convex subsets of a locally convex space , where is closed
 * and is compact, then there is a continuous real linear functional on such
 * that for some real number the inequalities , hold for all , , respectively.
 * In particular, a non-empty closed convex set in a locally convex space is the
 * intersection of all closed half-spaces containing it. A non-empty closed
 * convex subset of a closed convex set is called a face (or extremal subset) of
 * if any closed segment in with an interior point in lies entirely in ; a point
 * is called an extreme point of if the set is a face of . If is a compact
 * convex set in a locally convex space and is the set of its extreme points,
 * then the following conditions are equivalent for a set : 1) ; 2) ; and 3) for
 * any continuous real linear functional on . In particular, (the Krein–Mil'man
 * theorem). The set is a Baire space in the induced topology (that is, the
 * intersection of any sequence of open subsets of that are dense in is dense in
 * ), and for any there is a probability measure on such that and the measure
 * vanishes on all Baire subsets that do not intersect (if is metrizable, then )
 * (Choquet's theorem). Any continuous mapping of a compact convex set in a
 * locally convex space into itself has a fixed point (the Schauder–Tikhonov
 * theorem); a commuting family of continuous affine transformations of onto
 * itself (and an equicontinuous group of continuous affine transformations of
 * onto itself) has a fixed point (the Markov–Kakutani theorem).
 * 
 * One quite important branch of the theory of locally convex spaces is the
 * theory of linear operators on a locally convex space; in particular, the
 * theory of compact (also called completely-continuous), nuclear and Fredholm
 * operators (cf. Compact operator; Fredholm operator; Nuclear operator).
 * Closed-graph and open-mapping theorems have far-reaching generalizations in
 * the theory of locally convex spaces. A locally convex space is said to have
 * the approximation property if the identity mapping of into itself can be
 * uniformly approximated on pre-compact sets of by finite-rank continuous
 * linear mappings of into itself. If a locally convex space has the
 * approximation property, then it has a number of other remarkable properties.
 * In particular, in such a space any nuclear operator has a uniquely defined
 * trace. There are separable Banach spaces that do not have the approximation
 * property, but Banach spaces with a Schauder basis and subspaces of projective
 * limits of Hilbert spaces do have the approximation property. Some versions of
 * this property are of interest in the theory of completely-continuous and
 * Fredholm operators.
 * 
 * A notable role in the theory of locally convex spaces is played by methods of
 * homological algebra connected with the study of the category of locally
 * convex spaces and their continuous mappings, and also some subcategories of
 * this category. In particular, homological methods have made it possible to
 * solve a number of problems connected with the extension of linear mappings
 * and with the existence of a linear mapping into a given space that lifts a
 * mapping into a quotient space of this space, and also to study properties of
 * completions of quotient spaces in relation to the completions of the spaces
 * and .
 * 
 * Other important questions in the theory of locally convex spaces are: the
 * theory of integration of vector-valued functions with values in a locally
 * convex space (as a rule, a barrelled space); the theory of differentiation of
 * non-linear mappings between locally convex spaces; the theory of topological
 * tensor products of locally convex spaces and the theory of Fredholm operators
 * and nuclear operators. There is a detailed theory of a number of special
 * classes of locally convex spaces, such as a barrelled spaces (cf. Barrelled
 * space), bornological spaces (on which any semi-norm that is bounded on
 * bounded sets is continuous), reflexive and semi-reflexive spaces (the
 * canonical mapping of which into the strong second dual is a topological or
 * linear isomorphism, respectively), nuclear spaces (cf. Nuclear space), etc.
 * 
 * References [1] A.N. Kolmogorov,
 * "Zur Normierbarkeit eines allgemeinen topologischen linearen Raumes" Studia
 * Math. , 5 (1935) pp. 29–33 [2] N. Bourbaki,
 * "Elements of mathematics. Topological vector spaces" , Addison-Wesley (1977)
 * (Translated from French) [3] N. Bourbaki,
 * "Elements of mathematics. Integration" , Addison-Wesley (1975) pp.
 * Chapt.6;7;8 (Translated from French) [4] H.H. Schaefer,
 * "Topological vector spaces" , Macmillan (1966) [5] M.M. Day,
 * "Normed linear spaces" , Springer (1973) [6] N. Dunford, J.T. Schwartz,
 * "Linear operators. General theory" , 1 , Interscience (1958) [7] A. Pietsch,
 * "Nuclear locally convex spaces" , Springer (1972) (Translated from German)
 * [8] W.J. Robertson, "Topological vector spaces" , Cambridge Univ. Press
 * (1973) [9] R.R. Phelps, "Lectures on Choquet's theorem" , v. Nostrand (1966)
 * [10] P. Enflo,
 * "A counterexample to the approximation problem in Banach spaces" Acta. Math.
 * , 130 (1973) pp. 309–317 [11] A. Frölicher, W. Bucher,
 * "Calculus in vector spaces without norm" , Lect. notes in math. , 30 ,
 * Springer (1966) [12] V.P. Palmodov,
 * "Homological methods in the theory of locally convex spaces" Russian Math.
 * Surveys , 26 : 1 (1971) pp. 1–64 Uspekhi Mat. Nauk , 26 : 1 (1971) pp. 3–65
 * 
 * @author crow
 *
 */
public interface LocallyConvexSpace extends Space
{

}
