package math.space;

import math.algebra.geometry.ProjectiveVariety;

/**
 * 
 * a projective space is the set of lines through the origin of a vector space
 * V. The cases when V = R2 and V = R3 are the projective line and the
 * projective plane, respectively, where R denotes the field of real numbers, R2
 * denotes ordered pairs of real numbers, and R3 denotes ordered triplets of
 * real numbers.
 * 
 * The idea of a projective space relates to perspective, more precisely to the
 * way an eye or a camera projects a 3D scene to a 2D image. All points which
 * lie on a projection line (i.e., a "line-of-sight"), intersecting with the
 * entrance pupil of the camera, are projected onto a common image point. In
 * this case the vector space is R3 with the camera entrance pupil at the origin
 * and the projective space corresponds to the image points.
 * 
 * Projective spaces can be studied as a separate field in mathematics, but are
 * also used in various applied fields, geometry in particular. Geometric
 * objects, such as points, lines, or planes, can be given a representation as
 * elements in projective spaces based on homogeneous coordinates. As a result,
 * various relations between these objects can be described in a simpler way
 * than is possible without homogeneous coordinates. Furthermore, various
 * statements in geometry can be made more consistent and without exceptions.
 * For example, in the standard geometry for the plane, two lines always
 * intersect at a point except when the lines are parallel. In a projective
 * representation of lines and points, however, such an intersection point
 * exists even for parallel lines, and it can be computed in the same way as
 * other intersection points.
 * 
 * Other mathematical fields where projective spaces play a significant role are
 * topology, the theory of Lie groups and algebraic groups, and their
 * representation theories.
 * 
 * Projective space From Encyclopedia of Mathematics
 * 
 * The collection of all subspaces of an incidence system , where the elements
 * of the set are called points, the elements of the set are called lines and I
 * is the incidence relation. A subspace of is defined to be a subset of for
 * which the following condition holds: If and , then the set of points of the
 * line passing through and also belongs to . The incidence system satisfies the
 * following requirements:
 * 
 * 1) for any two different points and there exists a unique line such that and
 * ;
 * 
 * 2) every line is incident to at least three points;
 * 
 * 3) if two different lines and intersect at a point and if the following four
 * relations hold: , , , , then the straight lines passing through the pairs of
 * points and intersect.
 * 
 * A subspace is generated by a set of points in (written ) if is the
 * intersection of all subspaces containing . A set of points is said to be
 * independent if for any one has . An ordered maximal and independent set of
 * points of a subspace is called a basis of , and the number of its elements is
 * called the dimension of the subspace . A subspace of dimension is a point, a
 * subspace of dimension is a projective straight line, a subspace of dimension
 * is called a projective plane.
 * 
 * In a projective space the operations of addition and intersection of spaces
 * are defined. The sum of two subspaces and is defined to be the smallest of
 * the subspaces containing both and . The intersection of two subspaces and is
 * defined to be the largest of the subspaces contained in both and . The
 * dimensions of the subspaces , , of their sum, and of their intersection are
 * connected by the relation
 * 
 * For any there is a such that and ( is a complement of in ), and if , then
 * 
 * for any (Dedekind's rule), that is, with respect to the operation just
 * introduced the projective space is a complemented modular lattice.
 * 
 * A projective space of dimension exceeding two is Desarguesian (see Desargues
 * assumption) and hence is isomorphic to a projective space (left or right)
 * over a suitable skew-field . The (for example) left projective space of
 * dimension over a skew-field is the collection of linear subspaces of an
 * -dimensional left linear space over ; the points of are the lines of , i.e.
 * the left equivalence classes of rows consisting of elements of which are not
 * simultaneously equal to zero (two rows and are left equivalent if there is a
 * such that , ); the subspaces , , are the -dimensional subspaces . It is
 * possible to establish a correspondence between a left and a right projective
 * space under which to a subspace corresponds (the subspaces and are called
 * dual to one another), to an intersection of subspaces corresponds a sum, and
 * to a sum corresponds an intersection. If an assertion based only on
 * properties of linear subspaces, their intersections and sums is true for ,
 * then the corresponding assertion is true for . This correspondence between
 * the properties of the spaces and is called the duality principle for
 * projective spaces (see [2]).
 * 
 * A finite skew-field is necessarily commutative; consequently, a finite
 * projective space of dimension exceeding two and of order is isomorphic to the
 * projective space over the Galois field. The finite projective space contains
 * points and subspaces of dimension (see [4]).
 * 
 * A collineation of a projective space is a permutation of its points that maps
 * lines to lines so that subspaces are mapped to subspaces. A non-trivial
 * collineation of the projective space has at most one centre and at most one
 * axis. The group of collineations of a finite projective space has order
 * 
 * Every projective space admits a cyclic transitive group of collineations (see
 * [3]).
 * 
 * A correlation of a projective space is a permutation of subspaces that
 * reverses inclusions, that is, if , then . A projective space admits a
 * correlation only if it is finite-dimensional. An important role in projective
 * geometry is played by the correlations of order two, also called polarities
 * (Polarity). References [1] E. Artin, "Geometric algebra" , Interscience
 * (1957) MR1529733 MR0082463 Zbl 0077.02101 [2] W.V.D. Hodge, D. Pedoe,
 * "Methods of algebraic geometry" , 1 , Cambridge Univ. Press (1947) MR0028055
 * Zbl 0796.14002 Zbl 0796.14003 Zbl 0796.14001 Zbl 0157.27502 Zbl 0157.27501
 * Zbl 0055.38705 Zbl 0048.14502 [3] R. Dembowski, "Finite geometries" ,
 * Springer (1968) pp. 254 MR0233275 Zbl 0159.50001 [4] B. Segre,
 * "Lectures on modern geometry" , Cremonese (1961) MR0131192 Zbl 0095.14802
 * 
 * 
 * Comments
 * 
 * The real and complex projective spaces , respectively , of all real,
 * respectively complex, lines through the origin in , respectively , are the
 * Grassmann manifolds , (cf. Grassmann manifold).
 * 
 * has a CW-decomposition of exactly one cell in each even dimension.
 * Consequently, its homology is for and for .
 * 
 * Real projective space has a CW-decomposition with exactly one cell in each
 * dimension. For odd the homology groups are: , , ; ; for . For even the
 * homology groups are: ; , ; , .
 * 
 * The real projective plane can be obtained by glueing a disc along its
 * boundary to the boundary of a crosscap (i.e. a Möbius strip). An easy way to
 * see this is to view as obtained from a disc by identifying
 * diametrically-opposite boundary points. Now remove a central disc and cut and
 * glue as indicated below.
 * 
 * Figure: p075350a
 * 
 * The real projective plane cannot be imbedded in , but can be imbedded in .
 * Its Euler characteristic is 1. References [a1] O. Veblen, J.W. Young,
 * "Projective geometry" , 1–2 , Blaisdell (1938–1946) MR0179667 MR0179666
 * MR1519256 MR1506049 MR1500790 MR1500747 Zbl 0127.37604 Zbl 0018.32604 Zbl
 * 63.0693.02 Zbl 55.0413.02 Zbl 52.0732.01 Zbl 51.0591.05 Zbl 51.0569.04 Zbl
 * 49.0547.01 Zbl 48.0843.04 Zbl 47.0582.08 Zbl 41.0606.06 Zbl 39.0606.01 Zbl
 * 38.0562.01 [a2] R. Baer, "Linear algebra and projective geometry" , Acad.
 * Press (1952) MR0052795 Zbl 0049.38103
 * 
 * @author crow
 *
 * @param V
 *          a projective space is the set of lines through the origin of a
 *          vector space V
 */
public interface ProjectiveSpace<V extends VectorSpace<?>> extends Space, ProjectiveVariety
{

}
